apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-angular-example
  labels: 
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-angular-example
spec:
  params:
  - name: clusterBuilder
    value: spa
  source:
    git:
      url: https://github.com/mathias-ewald/tap-angular-example.git
      ref:
        branch: main
